DROP TABLE IF EXISTS USER_DETAILS;
DROP TABLE IF EXISTS CLIENT_METADATA;
CREATE TABLE CLIENT_METADATA(ID INT PRIMARY KEY, CLIENT_CODE VARCHAR(8) NOT NULL, CLIENT_NAME VARCHAR(64) NOT NULL, LOGO_URL VARCHAR(1024) NOT NULL,SERVICE_URL VARCHAR(1024) NOT NULL);
CREATE TABLE USER_DETAILS(ID INT PRIMARY KEY,CLIENT_METADATA_ID INT NOT NULL, USERNAME VARCHAR(64) NOT NULL, PASSWORD VARCHAR(64) NOT NULL, ADMIN BIT NOT NULL, FOREIGN KEY (CLIENT_METADATA_ID) REFERENCES CLIENT_METADATA(ID));